# Synthetic Data Generator Configuration

# Ollama connection settings
ollama:
  base_url: "http://localhost:11434"
  timeout: 120  # seconds

# Default generation settings
generation:
  model: "llama3.2:8b-instruct-q4_K_M"
  temperature: 0.7
  max_tokens: 500
  top_p: 0.9
  top_k: 40
  repeat_penalty: 1.1

# Output settings
output:
  directory: "output"
  format: "jsonl"  # Options: json, jsonl, csv
  timestamp: true  # Add timestamp to filename

# Batch processing
batch:
  size: 10  # Process this many at once
  delay: 0.5  # Seconds between batches (to avoid overwhelming the system)